default: &DEFAULT
  adapter: postgresql
  encoding: unicode
  host: <%= Rails.application.secrets.database["host"] %>
  username: <%= Rails.application.secrets.database["username"] %>
  password: <%= Rails.application.secrets.database["password"] %>

development:
  <<: *DEFAULT
  database: site_development

test:
  <<: *DEFAULT
  database: site_test

production:
  <<: *DEFAULT
  database: site_production

production_debug:
  <<: *DEFAULT
  database: site_production
